### ISSUE TITLE
Searching And Sorting Techniques

### ISSUE THREAD

**Issue by Abdulwahid7027** [souvikg544/DSA#65]
### Please assign it to me for Hacktoberfest.

**Comment by souvikg544** [comment]
Which techniques do you want to implement because most of them are already done @Abdulwahid7027

**Comment by Abdulwahid7027** [comment]
### I wanted to add bubble sort,insertion sort,selection sort in c language and linear search in java
### And also i want to arrange files subject wise or language wise

**Comment by 5SPriya404** [comment]
Hello sir,
please assign this to me.
I want to implement bubble sort ,selection sort,insertion sort in java.
